### ISSUE TITLE
Can't get it to run

### ISSUE THREAD

**Issue by Rossobimbo** [erdewit/heartwave#1]
i would love to see it running, as it seems an improvement of the other project i've been following for a while now.
but this is the error i get:
File "/usr/local/bin/heartwave", line 6, in <module>
    from heartwave.app import main
ImportError: cannot import name 'main'

any ideas?

**Comment by erdewit** [comment]
Thanks for the bug report. I had forgotten about the main entry point and this is added again in v0.9.1.
