### ISSUE TITLE
Invalid String format when running from terminal

### ISSUE THREAD

**Issue by version0chiro** [erdewit/heartwave#3]
timeStamp = datetime.datetime.now().strftime('%Y%m%d%_H%M%S_%f')
ValueError: Invalid format string

**Comment by erdewit** [comment]
What platform are you using?
The format string should be valid on all platforms, but perhaps your platform has issues with the %f part.

**Comment by version0chiro** [comment]
Yes I fixed it manually, probably due to the python version perhaps, would be great if you list it in the readme so people can get a heads up
